- alias: Sync Tasmota states
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: tasmota/cmnd/switch_wasmachine/serialsend5
        payload: "55aa0001000000"
    - service: mqtt.publish
      data:
        topic: tasmota/cmnd/switch_wasdroger/serialsend5
        payload: "55aa0001000000"
    - service: mqtt.publish
      data:
        topic: tasmota/cmnd/switch_vaatwasser/serialsend5
        payload: "55aa0001000000"
    - service: mqtt.publish
      data:
        topic: tasmota/cmnd/switch_koelkast/serialsend5
        payload: "55aa0001000000"
    - service: mqtt.publish
      data:
        topic: tasmota/cmnd/switch_vriezer/serialsend5
        payload: "55aa0001000000"
