homeassistant:
  name: "D&A"
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 12
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.1.0/24

discovery:
  ignore:
    - yeelight
sun:
updater:
frontend:
  themes: !include_dir_merge_named themes
conversation:
logbook:
zeroconf:
ffmpeg:
history:
config:
webhook:
system_health:
mobile_app:
map:
wake_on_lan:

notify:
  - name: all_devices
    platform: group
    services:
      - service: mobile_app_iphone
      - service: mobile_app_pocophone

ios:
  push:
    categories:
      - name: waste pickup
        identifier: "wastepickup"
        actions:
          - identifier: "DONE"
            title: "Klaar"
            destructive: no
          - identifier: "SNOOZE"
            title: "Snooze"
            destructive: yes

webostv:
  host: 192.168.1.106
  name: LG OLED65GX6LA
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret lg_oled_mac
      #broadcast_address: 192.168.1.255

cast:
  media_player:
    - host: 192.168.1.219

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

homekit:
  filter:
    include_domains:
      - light
      - switch

nefiteasy:
  devices:
  - serial: !secret nefit_serial
    accesskey: !secret nefit_access_key
    password: !secret nefit_password
    name: Verwarming

climate:
  - platform: intesishome
    username: !secret airconwithme_username
    password: !secret airconwithme_password
    device: airconwithme

utility_meter:
  daily_power_offpeak:
    source: sensor.dsmr_reading_electricity_delivered_1
    cycle: daily
  daily_power_peak:
    source: sensor.dsmr_reading_electricity_delivered_2
    cycle: daily
  daily_power_returned_offpeak:
    source: sensor.dsmr_reading_electricity_returned_1
    cycle: daily
  daily_power_returned_peak:
    source: sensor.dsmr_reading_electricity_returned_2
    cycle: daily
  daily_gas:
    source: sensor.gas_consumption
    cycle: daily
  monthly_power_offpeak:
    source: sensor.dsmr_reading_electricity_delivered_1
    cycle: monthly
  monthly_power_peak:
    source: sensor.dsmr_reading_electricity_delivered_2
    cycle: monthly
  monthly_power_returned_offpeak:
    source: sensor.dsmr_reading_electricity_returned_1
    cycle: monthly
  monthly_power_returned_peak:
    source: sensor.dsmr_reading_electricity_returned_2
    cycle: monthly
  monthly_gas:
    source: sensor.dsmr_consumption_gas_delivered
    cycle: monthly

variable:
  last_motion:
    value: "Unknown"
    restore: true
    attributes:
      icon: mdi:map-marker
      name: "Last motion"

automation: !include automations.yaml
automation old: !include_dir_merge_list automation/

person: !include_dir_merge_list persons/
zone: !include_dir_merge_list zones/
group: !include_dir_named groups/
media_player: !include_dir_merge_list mediaplayers/
binary_sensor: !include_dir_merge_list binary_sensors/
camera: !include_dir_merge_list cameras/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
light: !include_dir_merge_list light/
scene: !include_dir_list scenes/
shell_command: !include_dir_merge_named shell_command/
input_boolean: !include_dir_named input_boolean/
input_datetime: !include_dir_named input_datetime/
input_number: !include_dir_named input_number/
input_select: !include_dir_named input_select/
script: !include_dir_merge_named scripts/
timer: !include_dir_named timer/
weather: !include_dir_merge_list weather/

yeelight:
  devices:
    192.168.1.86:
      name: Woonkamerlamp linksvoor
      model: color1
    192.168.1.133:
      name: Woonkamerlamp rechtsvoor
      model: color1
    192.168.1.87:
      name: Toiletlamp
      model: color1
    192.168.1.138:
      name: Badkamerlamp
      model: color1
    192.168.1.18:
      name: Slaapkamer Jurjen
      model: color1
    192.168.1.176:
      name: Buitenlamp achter
      model: color1
    192.168.1.36:
      name: Overlooplamp
      model: color1

http:
  server_port: 8123
  base_url: !secret http_base_url

mqtt:
  broker: mqtt
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"

recorder:
  purge_interval: 1
  purge_keep_days: 4
  db_url: !secret homeassistant_recorder_db_url
