homeassistant:
  name: "D&A"
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 12
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  customize_glob:
    sensor.*_energy:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: energy
      state_class: measurement
    sensor.*_energy_returned:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: energy
      state_class: measurement
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.1.0/24

discovery:
  ignore:
    - yeelight
sun:
frontend:
  themes: !include_dir_merge_named themes
conversation:
logbook:
zeroconf:
stream:
ffmpeg:
history:
config:
webhook:
system_health:
mobile_app:
map:
wake_on_lan:
energy:
default_config:

notify:
  - name: all_devices
    platform: group
    services:
      - service: mobile_app_iphone_van_dennis
      - service: mobile_app_sm_a528b

homekit:
  advertise_ip: 192.168.0.20
  filter:
    include_domains:
      - light
    include_entities:
      - switch.salonkast_woonkamer
      - switch.tv
      - switch.schakelaar_buitenverlichting_voor
      - group.buitenverlichting_achter
      - switch.buitenverlichting_achtertuin
      - switch.buitenverlichting_overkapping
      - switch.fontein_achtertuin

climate:
  - platform: intesishome
    username: !secret airconwithme_username
    password: !secret airconwithme_password
    device: airconwithme

utility_meter:
  daily_energy_offpeak:
    source: sensor.dsmr_reading_electricity_delivered_1
    cycle: daily
  daily_energy_peak:
    source: sensor.dsmr_reading_electricity_delivered_2
    cycle: daily
  daily_energy_returned_offpeak:
    source: sensor.dsmr_reading_electricity_returned_1
    cycle: daily
  daily_energy_returned_peak:
    source: sensor.dsmr_reading_electricity_returned_2
    cycle: daily
  daily_gas:
    source: sensor.gas_consumption
    cycle: daily
  monthly_energy_offpeak:
    source: sensor.dsmr_reading_electricity_delivered_1
    cycle: monthly
  monthly_energy_peak:
    source: sensor.dsmr_reading_electricity_delivered_2
    cycle: monthly
  monthly_energy_returned_offpeak:
    source: sensor.dsmr_reading_electricity_returned_1
    cycle: monthly
  monthly_energy_returned_peak:
    source: sensor.dsmr_reading_electricity_returned_2
    cycle: monthly
  monthly_gas:
    source: sensor.dsmr_consumption_gas_delivered
    cycle: monthly

variable:
  last_motion:
    value: "Unknown"
    restore: true
    attributes:
      friendly_name: "Last motion"
      icon: mdi-map-marker

automation: !include automations.yaml
automation old: !include_dir_merge_list automation/

person: !include_dir_merge_list persons/
zone: !include_dir_merge_list zones/
group: !include_dir_named groups/
media_player: !include_dir_merge_list mediaplayers/
binary_sensor: !include_dir_merge_list binary_sensors/
camera: !include_dir_merge_list cameras/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
light: !include_dir_merge_list light/
scene: !include_dir_list scenes/
shell_command: !include_dir_merge_named shell_command/
input_boolean: !include_dir_named input_boolean/
input_datetime: !include_dir_named input_datetime/
input_number: !include_dir_named input_number/
input_select: !include_dir_named input_select/
script: !include_dir_merge_named scripts/
timer: !include_dir_named timer/
weather: !include_dir_merge_list weather/

yeelight:
  devices:
    192.168.4.127:
      name: Woonkamerlamp linksvoor
      model: color1
    192.168.94.49:
      name: Woonkamerlamp rechtsvoor
      model: color1
    192.168.6.128:
      name: Badkamerlamp
      model: color1
    192.168.1.238:
      name: Overlooplamp
      model: color1

http:
  server_port: 8123
  cors_allowed_origins:
    - !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8

mqtt:
  sensor:
    - name: "EV Energy Total"
      state_topic: "tasmota/tele/switch_ev/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Total"] }}'
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing 
    - name: "EV Energy Today"
      state_topic: "tasmota/tele/switch_ev/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Today"] }}'
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: measurement 
    - name: "EV Power"
      state_topic: "tasmota/tele/switch_ev/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Power"] }}'
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement 
    - name: "EV Voltage"
      state_topic: "tasmota/tele/switch_ev/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
      unit_of_measurement: "V"
      device_class: voltage
      state_class: measurement 
    - name: "EV Current"
      state_topic: "tasmota/tele/switch_ev/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Current"] }}'
      unit_of_measurement: "A"
      device_class: current
      state_class: measurement

recorder:
  purge_keep_days: 4
  db_url: !secret homeassistant_recorder_db_url

entity_controller:
  hallway_downstairs_light:
    sensor: binary_sensor.activity_in_hall_downstairs
    entity: switch.schakelaar_gang
    delay: 300
    block_timeout: 300
    sensor_type: duration
    sensor_resets_timer: True
  toilet_light:
    sensor: binary_sensor.activity_in_toilet
    entity: switch.schakelaar_toilet
    delay: 300
    block_timeout: 300
    sensor_type: duration
    sensor_resets_timer: True
  kitchen_light:
    sensor: binary_sensor.activity_in_kitchen
    entity: light.keukenspots
    delay: 300
    block_timeout: 300
    overrides:
      - input_boolean.automation_kitchen_disabled
    sensor_type: duration
    sensor_resets_timer: True
  garage_light:
    sensor: binary_sensor.activity_in_garage
    entity: light.garagelamp
    block_timeout: 300
    delay: 300
    sensor_type: duration
    sensor_resets_timer: True
  bijkeuken_light:
    sensor: binary_sensor.activity_in_bijkeuken
    entity: light.bijkeukenlamp
    block_timeout: 300
    delay: 300
    sensor_type: duration
    sensor_resets_timer: True

# influxdb:
#   api_version: "2"
#   host: influxdb
#   port: 8086
#   ssl: false
#   token: "HG_V28Fy4sgbkLn5jhbQeTCVLpGw1LA8I8DoehQV6HmsdBlCikH7zu7513B09uEQosRt-bFBf0mU3PZBGXEtCA=="
#   organization: local
#   bucket: home-assistant
#   precision: "s"
#   include:
#     entity_globs:
#       - sensor.dsmr*
#       - sensor.energy*
#       - sensor.daily_energy*
#       - sensor.monthly_energy*
#       - sensor.vaatwasser_*
#       - sensor.wasmachine_*
#       - sensor.wasdroger_*
#       - sensor.bv14220072_*
#       - sensor.temperature*
#       - sensor.light_sensor*
#       - sensor.buienradar_temperature
#       - sensor.d_a_total_money_lifetime
#       - sensor.humidity*
#       - sensor.solaredge*
#       - sensor.d_a_total_lifetime_energy_output
#       - sensor.d_a_total_output_power
#       - sensor.d_a_total_energy_today
