homeassistant:
  name: "D&A"
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 12
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.1.0/24

discovery:
  ignore:
    - yeelight
sun:
updater:
frontend:
conversation:
logbook:
zeroconf:
history:
config:
webhook:

zigbee2mqtt_networkmap:

panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

# logger:
#   default: info
#   logs:
#     pydeconz: debug
#     homeassistant.components.deconz: debug

climate:
  platform: nefit
  name: Verwarming
  serial: !secret nefit_serial
  accesskey: !secret nefit_access_key
  password: !secret nefit_password

variable:
  last_motion:
    value: 'Unknown'
    restore: true
    attributes:
      icon: mdi:map-marker
      name: "Last motion"

device_tracker: !include_dir_list device_tracker/

person: !include_dir_merge_list persons/

group: !include_dir_named groups/
media_player: !include_dir_merge_list mediaplayers/
binary_sensor: !include_dir_merge_list binary_sensors/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
light: !include_dir_merge_list light/
scene: !include_dir_list scenes/

yeelight:
  devices:
    192.168.1.86:
      name: Woonkamerlamp linksvoor
      model: color1
    192.168.1.133:
      name: Woonkamerlamp rechtsvoor
      model: color1
    192.168.1.87:
      name: Toiletlamp
      model: color1
    192.168.1.138:
      name: Badkamerlamp
      model: color1
    192.168.1.18:
      name: Slaapkamer Jurjen
      model: color1
    192.168.1.176:
      name: Slaapkamer Jesper
      model: color1
    192.168.1.36:
      name: Overlooplamp
      model: color1

input_boolean: !include_dir_named input_boolean/
input_select: !include_dir_named input_select/
input_datetime: !include_dir_named input_datetime/
input_number: !include_dir_named input_number/

timer: !include_dir_named timer/

automation: !include automations.yaml
automation old: !include_dir_merge_list automation/

weather: !include_dir_merge_list weather/

http:
  server_port: 8123
  ssl_certificate: !env_var HTTP_SSL_CERTIFICATE
  ssl_key: !env_var HTTP_SSL_KEY
  api_password: !secret homeassistant_api_password  
  base_url: !env_var HTTP_BASE_URL
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24

mqtt:
  broker: localhost
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

recorder:
  purge_interval: 1
  purge_keep_days: 4
  db_url: !secret homeassistant_recorder_db_url

rfxtrx:
  device: /dev/ttyUSB2

# tradfri:
#   host: !env_var TRADFRI_GATEWAY

influxdb:
  host: !secret influxdb_host
  port: 8086
  database: home-assistant
  username: !secret influxdb_username
  password: !secret influxdb_password
