background: var(--background-image)
custom_header:
  background: rgba(155, 155, 155, 0.25)
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
  compact_mode: true
  swipe_animate: fade
  swipe_prevent_default: true
resources:
- type: js
  url: /local/monster-card.js?v=0.0.2
- type: module
  url: /local/custom-lovelace/custom-header/custom-header.js?v=0.0.1
- type: module
  url: /local/simple-weather-card-bundle.js?v=0.6.0
- type: module
  url: /local/button-card.js?v=3.1.1
title: D&A
views:
- badges:
  - person.dennis
  - person.antsje
  - sensor.br_condition_2
  - sun.sun
  cards:
  - entities:
    - entity: light.hoekwoonkamerlamp
    - entity: light.middenwoonkamerlamp
    - entity: light.woonkamerlamp_linksvoor
    - entity: light.woonkamerlamp_rechtsvoor
    - entity: light.wordclock
    - entity: switch.salonkast_woonkamer
    - switch.tv
    show_header_toggle: true
    title: Woonkamer
    type: entities
  - entities:
    - light.keukenspots
    show_header_toggle: true
    title: Keuken
    type: entities
  - entities:
    - light.voordeurlamp_buiten
    - binary_sensor.deursensor_voordeur
    show_header_toggle: true
    title: Buiten
    type: entities
  - entities:
    - light.overlooplamp
    show_header_toggle: true
    title: Overloop
    type: entities
  - entities:
    - light.garagelamp
    - binary_sensor.deursensor_garage
    show_header_toggle: true
    title: Garage
    type: entities
  - entities:
    - light.toiletlamp
    show_header_toggle: true
    title: Toilet
    type: entities
  - entities:
    - light.badkamerlamp
    show_header_toggle: true
    title: Badkamer
    type: entities
  - card:
      title: Batterij bijna leeg
      type: entities
    filter:
      include:
      - attributes:
          battery: < 25
        entity_id: sensor.*battery*
    show_empty: false
    show_header_toggle: false
    type: custom:monster-card
  - entity: climate.verwarming
    type: thermostat
  - entity: weather.dark_sky
    name: Weather
    type: custom:simple-weather-card
  - card:
      title: Bewegingssensoren
      type: entities
    filter:
      include:
      - entity_id: binary_sensor.bewegingssensor*
        state: 'on'
    show_empty: false
    show_header_toggle: false
    type: custom:monster-card
  - entities:
    - sensor.non_recyclable_waste_pickup
    - sensor.organic_waste_pickup
    - sensor.paper_waste_pickup
    - sensor.plastic_waste_pickup
    show_header_toggle: false
    title: Afhaalophaalschema
    type: entities
  icon: mdi:home
  path: default_view
  title: Home
- badges: []
  cards:
  - entities:
    - input_datetime.wakeup_time
    - input_number.wakeup_turn_off_after
    - input_boolean.wakeup_enabled
    - input_boolean.wakeup_weekend
    show_header_toggle: true
    title: Wake-up lights
    type: entities
  - entities:
    - input_boolean.guest_mode
    show_header_toggle: true
    title: Instellingen
    type: entities
  icon: mdi:settings
  path: configuration
  title: Configuration
- badges: []
  cards:
  - entity: media_player.chromecast_woonkamer
    type: media-control
  - entity: media_player.denon_avr_x1300w
    type: media-control
  - entity: media_player.kodi_media_player
    type: media-control
  icon: mdi:play-box-outline
  path: media_players
  title: Media players
- badges:
  - sensor.zigbee2mqtt_bridge_state
  - timer.zigbee_permit_join
  cards:
  - entities:
    - automation.zigbee2mqtt_log_level
    title: Automation
    type: entities
  - entities:
    - input_boolean.zigbee_permit_join
    title: Input boolean
    type: entities
  - entities:
    - input_select.zigbee2mqtt_log_level
    title: Input select
    type: entities
  - entities:
    - switch.zigbee2mqtt_main_join
    title: Switch
    type: entities
  icon: mdi:rss-box
  path: zigbee2mqtt
  title: zigbee2mqtt
