title: D&A
views:
  - name: Home
    tab_icon: mdi:home
    cards:
      - type: entities
        title: Woonkamer
        entities:
          - light.hoekwoonkamerlamp_3
          - light.middenwoonkamerlamp
          - switch.woonkamerlamp_rechtsvoor
          - switch.tv
      - type: entities
        title: Keuken
        entities:
          - light.keukenspots
      - type: entities
        title: Buiten
        entities:
          - light.buitenlamp_voordeur
          - switch.voordeurschakelaar
      - type: entities
        title: Overloop
        entities:
          - light.overlooplamp_2
          - binary_sensor.motion_sensor_overloop
      - type: entities
        title: Garage
        entities:
          - light.garagelamp
          - binary_sensor.vpir_beweging_garage
      - type: entities
        title: Slaapkamer D&A
        entities:
          - light.slaapkamerlamp_da
      - type: entities
        title: Meterstanden
        entities:
          - sensor.power_consumption
          - sensor.power_production
          - sensor.hourly_gas_consumption
          - sensor.power_consumption_low
          - sensor.power_consumption_normal
          - sensor.power_production_low
          - sensor.power_production_normal
          - sensor.gas_consumption
      - type: entities
        title: Wake-up lights
        entities:
          - input_datetime.wakeup_time
          - input_number.wakeup_turn_off_after
          - input_boolean.wakeup_enabled
          - input_boolean.wakeup_weekend
      - type: entities
        title: Instellingen
        entities:
          - input_boolean.guest_mode
      - type: media-control
        entity: media_player.das_chromecast
      - type: media-control
        entity: media_player.denon_avrx1300w
  - name: All Entities
    tab_icon: mdi:settings
    cards:
      - type: entity-filter
        filter:
          - {}
        card_config:
          title: All Entities
