- alias: Verlichting aan na zonsondergang
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.zonsondergang
