- alias: 'Turn on some lights on rainy days'
  trigger:
    - platform: state
      entity_id: sensor.buienradar_condition
      to: 'rainy'
    - platform: numeric_state
      entity_id: sensor.buienalarm_precipitation
      above: 0
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: group.people
      state: 'home'
    - condition: time
      after: '12:00'
    - condition: sun
      before: sunset
  action:
    - service: scene.turn_on
      entity_id: scene.regenachtige_dag
- alias: 'Rain is over'
  trigger:
    - platform: state
      entity_id: sensor.buienradar_condition
      from: 'rainy'
    - platform: numeric_state
      entity_id: sensor.buienalarm_precipitation
      below: 0.1
      for:
        minutes: 10
  condition:
    - condition: sun
      before: sunset
      before_offset: '01:00:00'
  action:
    service: scene.turn_off
    entity_id: scene.regenachtige_dag
