- alias: Serreverlichting uit na zonsopkomst
  trigger:
    platform: sun
    event: sunrise
    offset: "+0:30:00"
  action:
    service: homeassistant.turn_off
    entity_id: group.serre
- alias: Serreverlichting aan voor zonsopkomst
  trigger:
  - platform: time
    at: "06:00:00"
  condition:
  - condition: template
    value_template: >
      {{ (as_timestamp(state_attr('sun.sun','next_rising')) + 1800) | timestamp_custom('%H:%M:%S') > "06:00:00" }}
  action:
    service: homeassistant.turn_on
    entity_id: group.serre