- alias: Buitenverlichting achter aan na zonsondergang
  trigger:
    platform: sun
    event: sunset
    offset: "0:30:00"
  action:
    service: homeassistant.turn_on
    entity_id: group.buitenverlichting_achter
