- alias: Buitenverlichting aan na zonsondergang
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: "off"
  action:
    service: homeassistant.turn_on
    entity_id: group.outside
