- platform: group
  name: Keukenspots
  entities:
    - light.keukenspot_1
    - light.keukenspot_2
    - light.keukenspot_3
    - light.keukenspot_4
    - light.keukenspot_5
    - light.keukenspot_6
