- platform: yeelight
  devices:
    192.168.1.86:
      name: Woonkamerlamp linksvoor
    192.168.1.133:
      name: Woonkamerlamp rechtsvoor
    192.168.1.87:
      name: Toiletlamp
    192.168.1.138:
      name: Badkamerlamp
    192.168.1.18:
      name: Slaapkamer Jurjen
    192.168.1.176:
      name: Slaapkamer Jesper