- platform: template
  sensors:
    daily_energy:
      friendly_name: Daily Energy
      unit_of_measurement: kWh
      value_template: "{{ states('sensor.daily_energy_offpeak')|float + states('sensor.daily_energy_peak')|float }}"
      device_class: energy
    daily_energy_returned:
      friendly_name: Daily Energy Returned
      unit_of_measurement: kWh
      value_template: "{{ states('sensor.daily_energy_returned_offpeak')|float + states('sensor.daily_energy_returned_peak')|float }}"
      device_class: energy
    monthly_energy:
      friendly_name: Monthly Energy
      unit_of_measurement: kWh
      value_template: "{{ states('sensor.monthly_energy_offpeak')|float + states('sensor.monthly_energy_peak')|float }}"
      device_class: energy
    monthly_energy_returned:
      friendly_name: Monthly Energy Returned
      unit_of_measurement: kWh
      value_template: "{{ states('sensor.monthly_energy_returned_offpeak')|float + states('sensor.monthly_energy_returned_peak')|float }}"
      device_class: energy