- platform: template
  sensors:
    status_vaatwasser:
      friendly_name: Status vaatwasser
      icon_template: >
        {% if (is_state('sensor.status_vaatwasser', 'running')) %} mdi:run
        {% elif (is_state('sensor.status_vaatwasser', 'idle')) %} mdi:toggle-switch
        {% else %} mdi:toggle-switch-off
        {% endif %}
      value_template: >
        {% set current_power = (states('sensor.vaatwasser_energy_power') | float) %}
        {% if (current_power) > 10 %} running
        {% elif (current_power > 0) %} idle
        {% else %} off
        {% endif %}
    status_wasmachine:
      friendly_name: Status wasmachine
      icon_template: >
        {% if (is_state('sensor.status_wasmachine', 'running')) %} mdi:run
        {% elif (is_state('sensor.status_wasmachine', 'idle')) %} mdi:toggle-switch
        {% else %} mdi:toggle-switch-off
        {% endif %}
      value_template: >
        {% set current_power = (states('sensor.wasmachine_energy_power') | float) %}
        {% if (current_power) > 25 %} running
        {% elif (current_power > 0) %} idle
        {% else %} off
        {% endif %}
    status_wasdroger:
      friendly_name: Status wasdroger
      icon_template: >
        {% if (is_state('sensor.status_wasdroger', 'running')) %} mdi:run
        {% elif (is_state('sensor.status_wasdroger', 'idle')) %} mdi:toggle-switch
        {% else %} mdi:toggle-switch-off
        {% endif %}
      value_template: >
        {% set current_power = (states('sensor.wasdroger_energy_power') | float) %}
        {% if (current_power) > 25 %} running
        {% elif (current_power > 0) %} idle
        {% else %} off
        {% endif %}
