- platform: template
  sensors:
    late_night:
      entity_id: sensor.time
      value_template: >
        {% set nowFormat = now().strftime("%H%M") -%}
        {{
          (
            (is_state("binary_sensor.workday_tomorrow", "on")) 
              and (
                ("22:00" | timestamp_custom("%H%M")) <= nowFormat
                or nowFormat < ("05:45" | timestamp_custom("%H%M"))
              )
          ) or (
            (is_state("binary_sensor.workday_tomorrow", "off"))
              and (
                nowFormat >= ("00:00" | timestamp_custom("%H%M"))
                and nowFormat < ("07:00" | timestamp_custom("%H%M"))
              )
          )
        }}
