- platform: template
  sensors:
    late_night:
      value_template: >
        {{
          (
            (now().isoweekday() > 0 and now().isoweekday() < 4) 
              and (
                strptime("23:00", "%H%M") <= now().strftime("%H:%M")
                or now().strftime("%H:%M") < strptime("05:45", "%H%M")
              )
          ) or (
            (now().isoweekday() == 0 or now().isoweekday() >= 4)
              and (
                now().strftime("%H:%M") >= strptime("00:00", "%H%M")
                and now().strftime("%H:%M") < strptime("07:00", "%H%M")
              )
          )
        }}
