- platform: template
  sensors:
    late_night:
      entity_id: sensor.time
      value_template: >
        {% set now = (now().strftime("%H%M") | int) -%}
        {{
          (
            (is_state("binary_sensor.workday_tomorrow", "on")) 
              and (
                (2200 <= now or now < 545)
              )
          ) or (
            (is_state("binary_sensor.workday_tomorrow", "off"))
              and (
                now >= 0 and now < 700
              )
          )
        }}
