- platform: template
  sensors:
    late_night:
      entity_id: sensor.time
      value_template: >
        {{
          (
            (is_state("binary_sensor.workday_tomorrow", "on")) 
              and (
                strptime("22:00", "%H%M") <= now().strftime("%H:%M")
                or now().strftime("%H:%M") < strptime("05:45", "%H%M")
              )
          ) or (
            (is_state("binary_sensor.workday_tomorrow", "off"))
              and (
                now().strftime("%H:%M") >= strptime("00:00", "%H%M")
                and now().strftime("%H:%M") < strptime("07:00", "%H%M")
              )
          )
        }}
