- platform: template
  sensors:
    late_night:
      value_template: >-
        {{
          (
            (now().isoweekday() >= 0 and now().isoweekday() < 5)
            and (
              strptime("23:00", "%H%M") < now().strftime("%H:%M")
              or now().strftime("%H:%M") < strptime("05:30", "%H%M")
            )
          ) or (
            (now().isoweekday() >= 5 and now().isoweekday() <= 6)
            and (
              now().strftime("%H:%M") > strptime("00:00", "%H%M")
              and now().strftime("%H:%M") < strptime("07:00", "%H%M")
            )
          )
        }}

