- platform: template
  sensors:
    motion_detected:
      value_template: >-
        {{ is_state("binary_sensor.bewegingssensor_garage", "on")
        or is_state("binary_sensor.bewegingssensor_overloop", "on")
        or is_state("binary_sensor.bewegingssensor_badkamer_motion", "on")
        or is_state("binary_sensor.bewegingssensor_keuken_motion", "on")
        or is_state("binary_sensor.bewegingssensor_salonkast_motion", "on")
        or is_state("binary_sensor.bewegingssensor_toilet_motion", "on")
        or is_state("binary_sensor.bewegingssensor_gang_motion", "on")
        or is_state("binary_sensor.bewegingssensor_woonkamer", "on") }}
    motion_detected_anywhere_except_overloop:
      value_template: >-
        {{ is_state("binary_sensor.bewegingssensor_garage", "on")
        or is_state("binary_sensor.bewegingssensor_badkamer_motion", "on")
        or is_state("binary_sensor.bewegingssensor_keuken_motion", "on")
        or is_state("binary_sensor.bewegingssensor_salonkast_motion", "on")
        or is_state("binary_sensor.bewegingssensor_toilet_motion", "on")
        or is_state("binary_sensor.bewegingssensor_gang_motion", "on")
        or is_state("binary_sensor.bewegingssensor_woonkamer", "on") }}
      delay_off: "00:05:00"
    house_idle:
      friendly_name: Geen beweging in huis
      value_template: >
        {{ is_state("binary_sensor.motion_detected", "off") }}
      delay_on: "00:15:00"
    motion_detected_in_last_hour:
      friendly_name: Beweging gedetecteerd in het afgelopen uur
      value_template: >
        {{ is_state("binary_sensor.motion_detected", "on") }}
      delay_off: "01:00:00"
    someone_in_the_house_in_last_hour:
      friendly_name: Iemand thuis in het afgelopen uur
      value_template: >
        {{ is_state("binary_sensor.motion_detected_in_last_hour", "on")
           or is_state("group.persons", "home") }}
    activity_in_bathroom:
      friendly_name: Activiteit in de badkamer
      value_template: >
        {{ is_state("binary_sensor.bewegingssensor_badkamer_motion", "on") }}
      delay_off: "00:03:00"
    activity_in_toilet:
      friendly_name: Activiteit in de toilet
      value_template: >
        {{ is_state("binary_sensor.bewegingssensor_toilet_motion", "on") }}
      delay_off: "00:01:00"
    activity_in_hall_downstairs:
      friendly_name: Activiteit in de gang
      value_template: >
        {{ is_state("binary_sensor.bewegingssensor_gang_motion", "on") }}
      delay_off: "00:01:00"
    activity_in_kitchen:
      friendly_name: Activiteit in de keuken
      value_template: >
        {{ is_state("binary_sensor.bewegingssensor_keuken_motion", "on") }}
      delay_off: "00:02:00"
    activity_in_bijkeuken:
      friendly_name: Activiteit in de bijkeuken
      value_template: >
        {{ is_state("binary_sensor.bewegingssensor_bijkeuken_motion", "on") }}
      delay_off: "00:02:00"
    activity_in_living_room:
      friendly_name: Activiteit in de woonkamer
      value_template: >
        {{ is_state("binary_sensor.bewegingssensor_woonkamer", "on") }}
      delay_off: "00:01:00"
    activity_overloop:
      friendly_name: Activiteit op de overloop
      value_template: >
        {{ is_state("binary_sensor.bewegingssensor_overloop", "on") }}
      delay_off: "00:01:00"
    activity_in_garage:
      friendly_name: Activiteit in de garage
      value_template: >
        {{ is_state("binary_sensor.bewegingssensor_garage", "on") }}
      delay_off: "00:01:00"
    living_room_presence:
      friendly_name: Aanwezigheid woonkamer
      value_template: >
        {{ is_state("device_tracker.dennis_apple_watch_tracker", "home") or is_state("device_tracker.dennis_apple_watch_tracker", "home") }}
      delay_off: "00:05:00"
