- platform: template
  sensors:
    motion_at_home:
      value_template: >-
        {%- if is_state("binary_sensor.bewegingssensor_keuken", "on")
        or is_state("binary_sensor.bewegingssensor_salonkast", "on")
        or is_state("binary_sensor.bewegingssensor_toilet", "on")
        or is_state("binary_sensor.bewegingssensor_woonkamer", "on")
        -%}
        True
        {%- else -%}
        False
        {%- endif %}