- platform: bayesian
  prior: 0.33
  name: "Sleep mode"
  probability_threshold: 0.95
  observations:
    - entity_id: media_player.denon_avrx1300w
      prob_given_true: 0.13
      prob_given_false: 0.75
      platform: state
      to_state: "on"
    - entity_id: media_player.denon_avrx1300w
      prob_given_true: 0.75
      prob_given_false: 0.25
      platform: state
      to_state: "off"
    - entity_id: media_player.lg_oled65gx6la
      prob_given_true: 0.13
      prob_given_false: 0.75
      platform: state
      to_state: "on"
    - entity_id: media_player.lg_oled65gx6la
      prob_given_true: 0.75
      prob_given_false: 0.25
      platform: state
      to_state: "off"
    - entity_id: binary_sensor.late_night
      prob_given_true: 0.75
      prob_given_false: 0.125
      platform: "state"
      to_state: "on"
    - entity_id: binary_sensor.late_night
      prob_given_true: 0.0
      prob_given_false: 1
      platform: "state"
      to_state: "off"
    - entity_id: "binary_sensor.motion_detected_in_last_hour"
      prob_given_true: 0.13
      prob_given_false: 0.9375
      platform: "state"
      to_state: "on"
    - entity_id: "binary_sensor.motion_detected_in_last_hour"
      prob_given_true: 0.88
      prob_given_false: 0.0625
      platform: "state"
      to_state: "off"
    - entity_id: "binary_sensor.living_room_presence"
      prob_given_true: 0.8
      prob_given_false: 0.05
      platform: state
      to_state: "off"
