- platform: template
  sensors:
    status_vaatwasser:
      friendly_name: Status vaatwasser
      delay_off:
        minutes: 1
      delay_on:
        seconds: 30
      icon_template: >
        {% if (is_state('binary_sensor.status_vaatwasser', 'on')) %} mdi:run
        {% else %} mdi:toggle-switch-off
        {% endif %}
      value_template: >
        {{ (states('sensor.vaatwasser_energy_power') | float) > 10 }}
    status_wasmachine:
      friendly_name: Status wasmachine
      delay_off:
        minutes: 1
        seconds: 30
      delay_on:
        seconds: 30
      icon_template: >
        {% if (is_state('binary_sensor.status_wasmachine', 'on')) %} mdi:run
        {% else %} mdi:toggle-switch-off
        {% endif %}
      value_template: >
        {{ (states('sensor.wasmachine_energy_power') | float) > 10 }}
    status_wasdroger:
      friendly_name: Status wasdroger
      delay_off:
        minutes: 1
      delay_on:
        seconds: 30
      icon_template: >
        {% if (is_state('binary_sensor.status_wasdroger', 'on')) %} mdi:run
        {% else %} mdi:toggle-switch-off
        {% endif %}
      value_template: >
        {{ (states('sensor.wasdroger_energy_power') | float) > 10 }}
