alias: "Media player off"
trigger:
  - platform: state
    entity_id: media_player.denon_avrx1300w
    to: 'off'
    from: 'on'
  - platform: state
    entity_id: media_player.das_chromecast
    to: 'off'
    from: 'on'
condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: input_boolean.lighting_automations
    state: 'on'
  - condition: state
    entity_id: input_boolean.adults_away
    state: 'off'
action:
    service: scene.turn_on
    entity_id: scene.living_room_normal