alias: "Popcorn Hour paused or turned off"
trigger:
  - platform: mqtt
    topic: popcorn-hour/playback/status
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: template
          value_template: '{{ trigger.payload_json.val == "pause" }}'
        - condition: template
          value_template: '{{ trigger.payload_json.val == "stop" }}'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.adults_away
      state: 'off'
action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal