- alias: "TV playing"
  trigger:
    - platform: state
      entity_id: media_player.lg_oled65gx6la
      to: 'playing'
  condition:
    - condition: sun
      after: sunset
      after_offset: "-01:00"
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
  action:
    - service: scene.create
      data:
        scene_id: living_room_before_dimming
        snapshot_entities: >-
          {{ ['Woonkamer'] | map('area_entities') | sum(start=[]) | select('match', 'light') | list }}
    - action: scene.turn_on
      target:
        entity_id: scene.woonkamer_gedimd
      data:
        transition: 2.5
- alias: "TV paused or turned off"
  trigger:
    - platform: state
      entity_id: media_player.lg_oled65gx6la
      to: 'paused'
      from: 'playing'
      for:
        seconds: 3
    - platform: state
      entity_id: media_player.lg_oled65gx6la
      to: 'off'
      from: 'playing'
      for:
        seconds: 3
    - platform: state
      entity_id: media_player.lg_oled65gx6la
      to: 'off'
      from: 'paused'
      for:
        seconds: 3
  condition:
    - condition: sun
      after: sunset
      after_offset: "-01:00"
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
  action:
    - action: scene.turn_on
      target:
        entity_id: scene.living_room_before_dimming
      data:
        transition: 2.5
    - service: adaptive_lighting.apply
      data:
        entity_id: switch.adaptive_lighting_eetkamer
    - service: adaptive_lighting.apply
      data:
        entity_id: switch.adaptive_lighting_d_a