- alias: "TV playing"
  trigger:
    - platform: state
      entity_id: media_player.lg_oled65gx6la
      to: 'playing'
      for:
        seconds: 10
  condition:
    - condition: sun
      after: sunset
      after_offset: "-01:00"
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
  action:
    # - service: scene.create
    #   data:
    #     scene_id: living_room_before_dimming
    #     snapshot_entities:
    #       - light.keukenspots
    #       - light.eetkamerlamp
    #       - light.hoekbanklamp_staand
    #       - light.vensterbanklamp
    #       - light.oosterse_lamp
    # - delay:
    #     seconds: 2
    - action: scene.turn_on
      target:
        entity_id: scene.woonkamer_gedimd
      data:
        transition: 2.5
- alias: "TV paused or turned off"
  trigger:
    - platform: state
      entity_id: media_player.lg_oled65gx6la
      from: 'playing'
      for:
        seconds: 2
    # - platform: state
    #   entity_id: media_player.lg_oled65gx6la
    #   to: 'idle'
    #   for:
    #     seconds: 2
  condition:
    - condition: sun
      after: sunset
      after_offset: "-01:00"
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
  action:
    - action: light.turn_on
      target:
        entity_id: light.keukenspots
    - action: light.turn_on
      target:
        entity_id: light.eetkamerlamp
    - action: light.turn_on
      target:
        entity_id: light.hoekbanklamp_staand
    - action: light.turn_on
      target:
        entity_id: light.vensterbanklamp
    - action: light.turn_on
      target:
        entity_id: light.oosterse_lamp
    - service: adaptive_lighting.apply
      data:
        entity_id: switch.adaptive_lighting_eetkamer
    - service: adaptive_lighting.apply
      data:
        entity_id: switch.adaptive_lighting_d_a
    # - action: scene.turn_on
    #   target:
    #     entity_id: scene.living_room_before_dimming
    # - service: adaptive_lighting.apply
    #   data:
    #     entity_id: switch.adaptive_lighting_eetkamer
    # - service: adaptive_lighting.apply
    #   data:
    #     entity_id: switch.adaptive_lighting_d_a
    # - service: adaptive_lighting.set_manual_control
    #   data:
    #     entity_id: switch.adaptive_lighting_eetkamer
    #     manual_control: false
    # - service: adaptive_lighting.set_manual_control
    #   data:
    #     entity_id: switch.adaptive_lighting_d_a
    #     manual_control: false