- alias: 'Adults away'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.person1_home
      to: 'off'
    - platform: state
      entity_id: input_boolean.person2_home
      to: 'off'
    - platform: state
      entity_id: input_boolean.person1_home
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: input_boolean.person2_home
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.person1_home
      state: 'off'
      for: 
        minutes: 2
    - condition: state
      entity_id: input_boolean.person2_home
      state: 'off'
      for: 
        minutes: 2
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.adults_away
