- alias: 'All away lights off during evening'
  trigger:
    - platform: state
      entity_id: group.people
      from: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: sun
      after: sunset
  action:
    - service: scene.turn_on
      entity_id: scene.s_avonds_weg
