- alias: "Send notification when Jesper arrives at school"
  trigger:
    platform: zone
    entity_id: person.jesper
    zone: zone.middelbare_school
    event: enter
  action:
    - service: notify.all_devices
      data:
        title: Jesper is op school
        message: "Jesper is zojuist veilig op school aangekomen"
        data:
          apns_headers:
            "apns-collapse-id": "people"
            tag: "people"

- alias: "Send notification when Jesper leaves from school"
  trigger:
    platform: zone
    entity_id: person.jesper
    zone: zone.middelbare_school
    event: leave
  action:
    - service: notify.all_devices
      data:
        title: Jesper is weggegaan van school
        message: "Jesper is zojuist weggegaan van school en is waarschijnlijk op weg naar huis"
        data:
          apns_headers:
            "apns-collapse-id": "people"
            tag: "people"
