- alias: "Send notification when Jurjen arrives at homework institute"
  trigger:
    platform: zone
    entity_id: person.jurjen
    zone: zone.nijenkamp
    event: enter
  action:
    - service: notify.all_devices
      data:
        title: Jurjen is bij Nijenkamp
        message: "Jurjen is zojuist veilig bij Nijenkamp aangekomen"
        data:
          apns_headers:
            "apns-collapse-id": "people"
            tag: "people"

- alias: "Send notification when Jurjen leaves homework institute"
  trigger:
    platform: zone
    entity_id: person.jurjen
    zone: zone.nijenkamp
    event: leave
  action:
    - service: notify.all_devices
      data:
        title: Jurjen is weggegaan bij Nijenkamp
        message: "Jurjen is zojuist weggegaan bij Nijenkamp en is waarschijnlijk op weg naar huis"
        data:
          apns_headers:
            "apns-collapse-id": "people"
            tag: "people"
