initial_state: 'on'
alias: 'person2 home'
trigger:
  - platform: state
    entity_id:
    - device_tracker.nexus_5x
    to: 'home'
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.person2_home
    state: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person2_home
