- alias: 'person1 away'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
      - device_tracker.nexus_5x
      to: 'not_home'
    - platform: state
      entity_id:
      - device_tracker.nexus_5x
      to: 'not_home'
      for:
        minutes: 5
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: input_boolean.person2_home
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.person2_home
