- alias: 'All away lights off during day'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.adults_away
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: sun
      before: sunset
  action:
    - service: scene.turn_on
      entity_id: scene.alle_lampen_uit
