- alias: Turn on bathroom light when there is motion
  trigger:
    platform: state
    entity_id: binary_sensor.presence_11
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.badkamerlamp
    data_template:
      brightness_pct: >
        {% if states.binary_sensor.late_night.state == 'on' %}2
        {% elif states.sensor.period_of_day.state != 'day' %}50
        {% else %}100
        {% endif %}
      rgb_color: ['{{255|int}}', '{{126|int if states.binary_sensor.late_night.state == "on" else 183|int}}', '{{0|int if states.binary_sensor.late_night.state == "on" else 123|int}}']
- alias: Turn off bathroom light x minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.presence_11
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.badkamerlamp
