- alias: Turn on bathroom light when there is motion
  trigger:
    platform: state
    entity_id: binary_sensor.presence_11
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.badkamerlamp
    data_template:
      brightness_pct: >
        {% if now().hour >= 22 and now().hour <= 23 %}25
        {% elif now().hour < 6 %}1
        {% else %}100
        {% endif %}
      rgb_color: >
        {% if now().hour >= 22 and now().hour <= 6 %}[255, 153, 0]
        {% else %}[ 255, 183, 123]
        {% endif %}
      color_temp: >
        {% if now().hour >= 22 and now().hour <= 6 %}588
        {% else %}312
        {% endif %}
- alias: Turn off bathroom light x minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.presence_11
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.badkamerlamp
