alias: Bedtime
initial_state: "off"
trigger:
  platform: time
  at: "00:30:00"
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
action:
  service: light.turn_off
  entity_id: group.all_lights