alias: Bedtijd (vr, za)
trigger:
  platform: time
  at: "01:00:00"
condition:
  condition: time
  weekday:
    - fri
    - sat
action:
  - service: scene.turn_on
    entity_id: scene.alle_lampen_op_begane_grond_uit
