alias: Bedtijd (vr, za)
trigger:
  platform: time
  at: "01:00:00"
condition:
  condition: time
  weekday:
    - fri
    - sat
action:
  - service: switch.turn_off
    entity_id: switch.woonkamerlamp_linksvoor
  - service: switch.turn_off
    entity_id: switch.woonkamerlamp_rechtsvoor
  - service: switch.turn_off
    entity_id: switch.woonkamerlamp_midden
  - service: switch.turn_off
    entity_id: switch.tv
  - service: light.turn_off
    entity_id: light.hoekwoonkamerlamp
  - service: light.turn_off
    entity_id: light.keukenspot1
  - service: light.turn_off
    entity_id: light.keukenspot2
  - service: light.turn_off
    entity_id: light.keukenspot3
  - service: light.turn_off
    entity_id: light.keukenspot4
  - service: light.turn_off
    entity_id: light.keukenspot5
  - service: light.turn_off
    entity_id: light.keukenspot6