alias: Bedtijd (ma, di, wo, do, zo)
trigger:
  platform: time
  at: "23:00:00"
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
action:
  - service: scene.turn_on
    entity_id: scene.alle_lampen_op_begane_grond_uit
