- alias: Voordeurlamp uit na zonsopkomst
  trigger:
    platform: sun
    event: sunrise
    offset: "+0:30:00"
  action:
    service: light.turn_off
    entity_id: light.buitenlamp_voordeur
- alias: Voordeurlamp aan na zonsondergang
  trigger:
    platform: sun
    event: sunset
    offset: "0:30:00"
  action:
    service: light.turn_on
    entity_id: light.buitenlamp_voordeur