alias: Voordeurlamp aan tussen zonsondergang en -opkomst
initial_state: "off"
trigger:
  platform: sun
  event: sunset
condition:
  condition: or
  conditions:
    - condition: sun
      after: sunset
      after_offset: "0:30:00"
    - condition: sun
      after: sunrise
      after_offset: "0:10:00"
action:
  service: light.turn_on
  entity_id: light.buitenlamp_voordeur