alias: Voordeurlamp aan na zonsondergang
trigger:
  platform: sun
  event: sunset
condition:
  condition: or
  conditions:
    - condition: sun
      after: sunset
      after_offset: "0:30:00"
action:
  service: light.turn_on
  entity_id: light.buitenlamp_voordeur