alias: Voordeurlamp uit na zonsopkomst
trigger:
  platform: sun
  event: sunrise
condition:
  condition: or
  conditions:
    - condition: sun
      before: sunrise
      before_offset: "-0:30:00"
action:
  service: light.turn_off
  entity_id: light.buitenlamp_voordeur