- alias: Turn on garage lights when there is motion
  trigger:
    platform: state
    entity_id: binary_sensor.bewegingssensor_garage
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.garage
- alias: Turn off garage lights x minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.bewegingssensor_garage
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.garage
