- alias: Holiday lights on during weekends
  trigger:
    platform: time
    at: "08:00:00"
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: switch.turn_on
      entity_id: switch.schakelaar_kerstboom