- alias: Turn on kitchen lights when there is motion
  trigger:
    platform: state
    entity_id: binary_sensor.presence_11
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.keukenspots
