- alias: Turn on kitchen lights when there is motion
  trigger:
    platform: state
    entity_id: binary_sensor.presence_11
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.keukenspots
- alias: Turn off kitchen lights x minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.presence_11
    to: 'off'
    for:
      minutes: 1
  action:
    service: light.turn_off
    entity_id: light.keukenspots
