- alias: "Send notification when refrigerator switch is turned off"
  trigger:
    platform: state
    entity_id: switch.schakelaar_koelkast
    to: "off"
    for:
      minutes: 1
  action:
    - service: notify.all_devices
      data:
        title: De schakelaar van de koelkast is uitgeschakeld
        message: "Controleer de schakelaar voordat alles ontdooit!"

- alias: "Send notification when refrigerator drawers no power"
  trigger:
    platform: state
    entity_id: sensor.koelkast_energy_current
    to: "0"
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: switch.schakelaar_koelkast
      state: "on"
  action:
    - service: notify.all_devices
      data:
        title: De koelkast lijkt geen stroom te verbruiken
        message: "Controleer de koelkast voordat alles ontdooit!"
