- alias: 'Turn on some lights on rainy days'
  trigger:
    - platform: state
      entity_id: sensor.br_condition
      to: 'rainy'
  condition:
    - condition: state
      entity_id: group.people
      state: 'home'
    - condition: time
      after: '14:00'
    - condition: sun
      before: sunset
  action:
    - service: scene.turn_on
      entity_id: scene.regenachtige_dag
- alias: 'Rain is over'
  trigger:
    - platform: state
      entity_id: sensor.br_condition
      from: 'rainy'
  condition:
    - condition: sun
      before: sunset
      before_offset: '01:00:00'
  action:
    service: scene.turn_off
    entity_id: scene.regenachtige_dag
