alias: 'Turn on some lights on rainy days'
trigger:
  - platform: state
    entity_id: sensor.precip_intensity
    to: 'rain'
condition:
  conditions:
    - condition: state
      entity_id: input_boolean.adults_away
      state: 'off'
    - condition: time
      after: '14:00'
    - condition: sun
      before: sunset
action:
  - service: scene.turn_on
    entity_id: scene.regenachtige_dag