- alias: Alles uit na indrukken knop bij voordeur
  trigger:
    platform: state
    entity_id: switch.voordeurschakelaar
    from: "off"
    to: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.woonkamerlamp_linksvoor
    - service: switch.turn_off
      entity_id: switch.woonkamerlamp_rechtsvoor
    - service: switch.turn_off
      entity_id: switch.woonkamerlamp_midden
    - service: switch.turn_off
      entity_id: switch.tv
    - service: light.turn_off
      entity_id: light.hoekwoonkamerlamp
    - service: light.turn_off
      entity_id: light.keukenspot_1
    - service: light.turn_off
      entity_id: light.keukenspot_2
    - service: light.turn_off
      entity_id: light.keukenspot_3
    - service: light.turn_off
      entity_id: light.keukenspot_4
    - service: light.turn_off
      entity_id: light.keukenspot_5
    - service: light.turn_off
      entity_id: light.keukenspot_6