- alias: Turn on overloop lights when there is motion
  trigger:
    platform: state
    entity_id: binary_sensor.bewegingssensor_overloop
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.overlooplamp
    data_template:
      brightness_pct: >
        {% if states.binary_sensor.late_night.state == 'on' %}2
        {% else %}75
        {% endif %}
      # rgb_color: ['{{255|int}}', '{{126|int if states.binary_sensor.late_night.state == "on" else 183|int}}', '{{0|int if states.binary_sensor.late_night.state == "on" else 123|int}}']
      color_temp: >
        {% if states.binary_sensor.late_night.state == 'on' %}560
        {% else %}275
        {% endif %}
- alias: Turn off overloop lights x minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.bewegingssensor_overloop
    to: 'off'
    for:
      minutes: 2
  action:
    service: light.turn_off
    entity_id: light.overlooplamp
