- alias: Turn on overloop lights when there is motion
  trigger:
    platform: state
    entity_id: binary_sensor.bewegingssensor_overloop
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.overloop
    data_template:
      brightness_pct: >
        {% if now().hour >= 22 and now().hour <= 23 %}25
        {% elif now().hour < 6 %}1
        {% else %}100
        {% endif %}
- alias: Turn off overloop lights x minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.bewegingssensor_overloop
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.overloop
