alias: Overlooplamp uit gedurende dag
trigger:
  platform: state
  entity_id: light.overlooplamp
  to: 'on'
condition:
  - condition: sun
    after: sunrise
    after_offset: "02:00:00"
  - condition: sun
    before: sunset
    before_offset: "-01:00:00"
action:
  - service: light.turn_off
    entity_id: light.overlooplamp
