- alias: 'Rain is over'
  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'None'
  condition:
    - condition: sun
      before: sunset
      before_offset: '01:00:00'
  action:
    service: scene.turn_off
    entity_id: scene.regenachtige_dag
