- alias: Turn on salonkast lights when there is motion
  trigger:
    platform: state
    entity_id: binary_sensor.bewegingssensor_salonkast
    to: 'on'
  action:
    - service: timer.start
      entity_id: timer.salonkast_motion
    - service: switch.turn_on
      entity_id: switch.salonkast_woonkamer
- alias: Turn off salonkast lights after timer
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.salonkast_motion
  action:
    service: switch.turn_off
    entity_id: switch.salonkast_woonkamer
