- alias: Restore the lights in the evening when someone returns home
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.people
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.lighting_automations
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: sun
      after: sunset
  action:
    - service: scene.turn_on
      entity_id: scene.zonsondergang
