- alias: Turn on toilet light when there is motion
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_toilet
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.toiletlamp
- alias: Turn off toilet light x minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_toilet
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.toiletlamp
