- alias: "Send notification when dishwasher is done"
  trigger:
    platform: state
    entity_id: binary_sensor.status_vaatwasser
    to: "off"
    for:
      minutes: 1
  action:
    - service: notify.all_devices
      data:
        title: De vaatwasser is klaar!
        message: "Pak de spullen maar uit, dan is ie weer klaar om ingeladen te worden..."
        data:
          apns_headers:
            "apns-collapse-id": "vaatwasser"
            tag: "vaatwasser"
