- alias: "Send notification when dishwasher is done"
  trigger:
    platform: state
    entity_id: sensor.status_vaatwasser
    from: "Running"
    to: "Idle"
    for:
      minutes: 1
  action:
    - service: notify.all_devices
      data:
        title: De vaatwasser is klaar!
        message: "Pak de spullen zo maar uit, dan is de keuken weer netjes..."
