- alias: "Send notification when washing machine is done"
  trigger:
    platform: state
    entity_id: binary_sensor.status_wasmachine
    to: "off"
    for:
      minutes: 1
  action:
    - service: notify.all_devices
      data:
        title: De wasmachine is klaar!
        message: "Snel de kleren eruit, anders ruikt het straks niet zo fris meer..."
        data:
          apns_headers:
            "apns-collapse-id": "wasmachine"
            tag: "wasmachiner"
