- alias: "Send notification when washing machine is done"
  trigger:
    platform: state
    entity_id: sensor.status_wasmachine
    from: "Running"
    to: "Idle"
    for:
      minutes: 1
  action:
    - service: notify.all_devices
      data:
        title: De wasmachine is klaar!
        message: "Snel de kleren eruit, anders ruikt het straks niet zo fris meer..."
