- alias: "Send notification when plastic waste pickup is tomorrow"
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.waste_pickup_notification_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.waste_pickup_notification_enabled
      state: "on"
    - condition: and
      conditions:
        - condition: state
          entity_id: sensor.plastic_waste_pickup_custom
          state: "Morgen"
  action:
    - service: notify.all_devices
      data:
        title: Oranje container aan de weg zetten
        message: "{{ state_attr('sensor.plastic_waste_pickup_custom', 'pickup_day') }} wordt de container voor plasticafval geleegd."
        data:
          push:
            category: "wastepickup"
          action_data:
            entity_id: sensor.plastic_waste_pickup_custom

- alias: "Send notification when organic waste pickup is tomorrow"
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.waste_pickup_notification_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.waste_pickup_notification_enabled
      state: "on"
    - condition: and
      conditions:
        - condition: state
          entity_id: sensor.organic_waste_pickup_custom
          state: "Morgen"
  action:
    - service: notify.all_devices
      data:
        title: Groene container aan de weg zetten
        message: "{{ state_attr('sensor.organic_waste_pickup_custom', 'pickup_day') }} wordt de container voor groenafval geleegd."
        data:
          push:
            category: "wastepickup"
          action_data:
            entity_id: sensor.organic_waste_pickup_custom

- alias: "Send notification when non-recyclable waste pickup is tomorrow"
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.waste_pickup_notification_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.waste_pickup_notification_enabled
      state: "on"
    - condition: and
      conditions:
        - condition: state
          entity_id: sensor.non_recyclable_waste_pickup_custom
          state: "Morgen"
  action:
    - service: notify.all_devices
      data:
        title: Grijze container aan de weg zetten
        message: "{{ state_attr('sensor.non_recyclable_waste_pickup_custom', 'pickup_day') }} wordt de container voor restafval geleegd."
        data:
          push:
            category: "wastepickup"
          action_data:
            entity_id: sensor.non_recyclabe_waste_pickup_custom

- alias: "Send notification when paper waste pickup is tomorrow"
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.waste_pickup_notification_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: state
      entity_id: input_boolean.waste_pickup_notification_enabled
      state: "on"
    - condition: and
      conditions:
        - condition: state
          entity_id: sensor.paper_waste_pickup_custom
          state: "Morgen"
  action:
    - service: notify.all_devices
      data:
        title: Blauwe container aan de weg zetten
        message: "{{ state_attr('sensor.paper_waste_pickup_custom', 'pickup_day') }} wordt de container voor papierafval geleegd."
        data:
          push:
            category: "wastepickup"
          action_data:
            entity_id: sensor.paper_waste_pickup_custom
